/**:
  ros__parameters:
    camera/autorecord: false
    camera/ev_compensation: 9
    camera/hdr: true
    camera/max_zoom_speed: 2.0
    camera/mode: 0
    camera/streaming: 0
    camera/style: 0
    drone/banked_turn: false
    drone/camera_operated: false
    drone/max_altitude: 2.0
    drone/max_distance: 42.0
    drone/max_horizontal_speed: 1.0
    drone/max_pitch_roll: 10.0
    drone/max_pitch_roll_rate: 300.0
    drone/max_vertical_speed: 1.0
    drone/max_yaw_rate: 180.0
    gimbal/max_speed: 180.0
    home/autotrigger: true
    home/ending_behavior: 1
    home/hovering_altitude: 10.0
    home/min_altitude: 20.0
    home/precise: true
    home/type: 4
    storage/download_folder: ~/Pictures/Anafi
    use_sim_time: false
