image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [940.95566,   0.     , 668.19425,
           0.     , 940.77709, 304.30803,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.037331, -0.022316, -0.003906, 0.007835, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [953.69763,   0.     , 677.85052,   0.     ,
           0.     , 960.32007, 301.13726,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
