uint8 mode 0 			# photo mode {0: single shot; 1: bracketing - burst of frames with a different exposure, 2: burst of frames; 3: time-lapse - frames at a regular time interval; 4: GPS-lapse - frames at a regular GPS position interval}
uint8 photo_format 1 		# photo format {0: full resolution, not dewarped; 1: rectilinear projection, dewarped}
uint8 file_format 0 		# file format {0: jpeg; 1: dng; 2: jpeg and dng}
uint8 burst 5 			# burst value {0: 14 picture over 4 second; 1: 14 picture over 2 second; 2: 14 picture over 1 second; 3: 10 picture over 4 second; 4: 10 picture over 2 second; 5: 10 picture over 1 second; 6: 4 picture over 4 second; 7: 4 picture over 2 second; 8: 4 picture over 1 second}
uint8 bracketing 6 		# bracketing value {0: 3 frames with EV compensation of {-1, 0, +1}; 1: 3 frames with EV compensation of {-2, 0, +2}; 2: 3 frames with EV compensation of {-3, 0, +3}; 3: 5 frames with EV compensation of {-2, -1, 0, +1, +2}; 4: 5 frames with EV compensation of {-3, -1, 0, +1, +3}; 5: 5 frames with EV compensation of {-3, -2, 0, +2, +3}; 6: 7 frames with EV compensation of {-3, -2, -1, 0, +1, +2, +3}}
float32 capture_interval 	# time-lapse interval value [in seconds], when mode==3; GPS-lapse interval value [in meters], when the mode==4; ignored in other modes
---
string media_id 		# media id
