float64 latitude	# latitude to look at [deg]
float64 longitude 	# longitude to look at [deg]
float64 altitude	# altitude to look at [m]
bool locked_gimbal 	# {true: gimbal is locked on the POI; false: gimbal is freely controllable}
---
